# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev", "main", "Iteration-2" ]
  pull_request:
    branches: [ "dev", "main", "Iteration-2" ]

env:
  docker_username: spedsbjerg
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  docker_repo: rarediseasepredicter
  GIT_COMMIT: ${{ github.sha }}

jobs:
  BuildBackend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./RareDiseasePredicter/RareDiseasePredicter
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  PushToDucker:
    runs-on: ubuntu-lastest
    needs: BuildBackend
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3

      - name: Login To DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{env.docker_username}}
          password: ${{env.docker_password}}

      - name: BuildBackend
        uses: docker/build-push-action@v2
        with:
          context: ./RareDiseasePredicter/RareDiseasePredicter
          push: true
          tags: spedsbjerg/rarediseasepredicter:Backend
  